version: '3.1'
services:
  stats-server:
    image: explore-with-me-stat
    build:
      context: stat/.
      dockerfile: Dockerfile
    container_name: explore-with-me-stat
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  stats-db:
    image: postgres:14-alpine
    container_name: db-postgres-stat
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure