CREATE SCHEMA IF NOT EXISTS schema;

CREATE TABLE IF NOT EXISTS endpoints
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app               VARCHAR(255)                            NOT NULL,
    uri               VARCHAR(512)                            NOT NULL,
    ip                VARCHAR(512)                            NOT NULL,
    timestamp_request TIMESTAMP                               NOT NULL
);
